export const SkillData = [
    {
        id: 1,
        name: "Html 5",
        Image: "/html.png",
        width: 80,
        height: 80,
    },
    {
        id: 2,
        name: "Css",
        Image: "/css.png",
        width: 80,
        height: 80,
    },
    {
        id: 3,
        name: "JavaScript",
        Image: "/js.png",
        width: 80,
        height: 80,
    },
    {
        id: 4,
        name: "Tailwind Css",
        Image: "/tailwind.png",
        width: 80,
        height: 80,
    },
    {
        id: 5,
        name: "React",
        Image: "/react.png",
        width: 80,
        height: 80,
    },
    {
        id: 6,
        name: "TypeScript",
        Image: "/ts.png",
        width: 80,
        height: 80,
    },
    {
        id: 7,
        name: "Next js 13",
        Image: "/next.png",
        width: 80,
        height: 80,
    },
    {
        id: 8,
        name: "Framer Motion",
        Image: "/framer.png",
        width: 80,
        height: 80,
    },
    {
        id: 9,
        name: "Git",
        Image: "/Git.png",
        width: 80,
        height: 80,
    },
    {
        id: 10,
        name: "Github",
        Image: "/Github.png",
        width: 80,
        height: 80,
    },
    {
        id: 11,
        name: "Java",
        Image: "/Java.png",
        width: 80,
        height: 80,
    },
    {
        id: 12,
        name: "Springboot",
        Image: "/Springboot.png",
        width: 80,
        height: 80,
    },
];

export const Projects = [
    {
        id: "1",
        title: "I-Key-Ah!",
        text: "Réalisé avec Springboot et Angular, ce projet a été créé en deux équipes de trois. La première partie du projet une équipe travaillait sur le front-end et l'autre sur le back-end. La deuxième partie de la semaine, les deux équipes se sont interchangées. Ce site permet de : Afficher les différents produits du magasin de meubles / Filtrer ces meubles par prix / Afficher plus d'informations d'un meuble sur la page dynamiquement.",
        objectives:
            "Création d'un site from scratch / Liaison entre l'équipe back-end et front-end / Première utilisation de frameworks (Spring Boot, Angular et Tailwind) / Gérer et créer des routes entre la DB et le front. ",
        nbpeople: "6",
        time: "7",
        language: "Java, Srping Boot, Angular, Typescript",
        src: "/ikeyah.png",
    },
    {
        id: "2",
        title: "Reseau social",
        text: "Nous sommes parties avec une base de code déjà fournie pour le projet. nous avons fait beaucoup de code review et de refacoring pour le commencement du projet. Notre réseau social nous permet de : Se connecter à son compte, aller sur le mur d'une autre personne et poster un message sur le mur de cette personne puis se déconnecter.",
        objectives:
            "Utiliser un serveur (avec WAMP). Apprendre à faire des requêtes SQL avec MySQL. Gérer une base de données avec PHP MyAdmin et gérer des session PHP.",
        nbpeople: "3",
        time: "7",
        language: "PHP, CSS",
        src: "/RS_PHP.png",
    },
    {
        id: "3",
        title: "Totally Chill",
        text: "Une extension Chromium avec différentes fonctions : programmer des rappels personnalisés avec un message et une heure précise / affichage de phrases aléatoires de Chuck Norris et/ou phrases aléatoires pour nous rappeller de prendre des pauses, de s'étirer, de boire de l'eau ... J'ai réalisé le logo et le front de notre extension dans la charte graphique des Totally Spies",
        objectives:
            "Comprendre comment fonctionne une extension avec son manifest, utilisation du shadowDOM. Utilisation des fonctionnalités chromium pour créer des notifications.",
        nbpeople: "3",
        time: "7",
        language: "HTML, SCSS, JS",
        src: "/Extension_totally_chill.png",
    },
    {
        id: "4",
        title: "Lieux de tournages à Paris",
        text: "Un site avec une carte interactive sur laquelle sont placés des marqueurs représentant les lieux de tournage, en fonction du film recherché. Utilisation de l'API de géocalisation Leaflet et l'API publique de la ville de Paris pour les lieux de tournages à Paris depuis 2016.",
        objectives:
            "Comprendre et apprendre à utiliser une API et manipuler des données. Utilisation du CSS pour rendre un site attractif. Apprendre de nouvelles fonctionnalités, comme les fonctions asynchrones en JavaScript. Attribuer des évènements à des éléments de notre HTML.",
        nbpeople: "3",
        time: "7",
        language: "HTML, CSS, JS",
        src: "/Dataviz.png",
    },
    {
        id: "5",
        title: "JumpyCat",
        text: "Premier projet de programmation. Un platformer en 2D avec un chat en personnage principal et des objets collectables. Le but est de se déplacer dans la map et sur des plateformes pour récupérer tous les poissons (20).",
        objectives:
            "Nos objectifs : appréhender un premier langage (LUA). Créer un petit jeu et prendre du plaisir dans la programmation",
        nbpeople: "3",
        time: "7",
        language: "LUA",
        src: "/game.gif",
    },
    {
        id: "6",
        title: "CROM Association",
        text: "Premier projet personnel pour l'association CROM qui organise des concerts à Angers et Nantes.",
        objectives:
            "Découverte de React, affichage d'évènements et de groupes avec leurs reseaux sociaux et formulaire pour l'inscription au tremplin de l'asso.",
        nbpeople: "1",
        time: "Work In Progress",
        language: "React, JavaScript, Tailwind",
        src: "/CROM.png",
    },
];
